import Head from "next/head";

import { useProduct } from "@/store";
import Link from "next/link";
export { getServerSideProps } from "@/store";

export default function Home() {
  const { products, business } = useProduct();

  return (
    <div>
      <Head>
        <title>Products</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-white text-6xl">{business[0].title_ar}</h1>
      <h1
        className="text-white text-6xl"
        style={{
          color: business[0].mainColor,
        }}
      >
        {business[0].title_en}
      </h1>
      <div className="grid grid-cols-3 gap-10 p-10">
        {products ? (
          products.map((p) => (
            <a href={p.item_uuid}>
              <div key={p.item_uuid}>
                <img
                  alt={p.title}
                  src={`http://om.sharray.io:8899/${p.image}`}
                />
                <h2>{p.title}</h2>
              </div>
            </a>
          ))
        ) : (
          <p>No products found.</p>
        )}
      </div>
    </div>
  );
}
